title: Self Branding Woes
email: hello@selfbrandingwoes.com
description: "A blog about the process of creating a new brand and website for my own business, Katherine Cory Design."
author:
  email: hello@selfbrandingwoes.com
  twitter: katherinecory
  github: katherinecory
baseurl: ""
url: "http://selfbrandingwoes.com"
safe: true
sass:
  sass_dir: _sass
  style: :compressed
gems: [github-pages, jekyll-compass, singularitygs, toolkit, breakpoint]
