title: Self Branding Woes
email: hello@selfbrandingwoes.com
description: "A blog about the process of creating a new brand and website for my own business, Katherine Cory Design."
author:
  email: hello@selfbrandingwoes.com
  twitter: katherinecory
  github: katherinecory
baseurl: ""
url: "http://selfbrandingwoes.com"
safe: true
exclude: [assets/sass]
permalink: pretty
